### ISSUE TITLE
Cannot read permission denied exception.

### ISSUE THREAD

**Issue by mrlinnth** [tohidplus/laravel-vue-translation#3]
Receiving this error.

```
   RuntimeException 

  Cannot read the file "/home/mrlinnth/www/laravel/resources/lang": permission denied (The web server user cannot read files, chmod needed)

  at vendor/elementaryframework/fire-fs/src/FireFS/FireFS.php:413
    409▕         $msg = "Cannot {$action} the file \"{$path}\": permission denied";
    410▕         if (!$this->isRemote($path)) {
    411▕             $msg .= " (The web server user cannot {$action} files, chmod needed)";
    412▕         }
  ➜ 413▕         return new \RuntimeException($msg);
    414▕     }
    415▕ 
    416▕     /**
    417▕      * Write in the file

      +20 vendor frames 
  21  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

Fixed it by changing `->setPath('./resources/lang')` to `->setPath('../resources/lang')`
in `src/Console/Commands/Translation.php`.

---

Sorry. Forgot to mention my environment.

"laravel/framework": "^8.12",
"tohidplus/laravel-vue-translation": "^2.0"

Linux Mint 20
php 7.4

**Comment by tohidplus** [comment]
Thank you for reporting this bug.
Actually, that was because of a new version of the FireFS. I downgraded the FIreFs to `1.0.0` and everything worked like a charm.
I released the patch version for this package which is `2.0.1`, now you can update and enjoy it.
