### ISSUE TITLE
how about fallback_locale ?

### ISSUE THREAD

**Issue by angryalf** [tohidplus/laravel-vue-translation#6]
Hi!

how about fallback_locale for?

**Comment by tohidplus** [comment]
Hi, can you please explain it more clear?

**Comment by angryalf** [comment]
In Laravel config we have 'fallback_locale', it uses if current language do not have translation and then uses this 'fallback_locale' instead display 'key' and if this missed, only then displays 'key'.... make sense?

**Comment by tohidplus** [comment]
Ok. it's a very good idea, I would be glad if you want to add this feature to my package and have a contribution.

**Comment by tohidplus** [comment]
Thank you for your contribution. Your new feature has been added to the version `2.1.0`
